// Export all documentation pages
export { default as DocsIndex } from './DocsIndex'
export { default as HeaderDoc } from './HeaderDoc'
export { default as SplashScreenDoc } from './SplashScreenDoc'
export { default as InfiniteMarqueeDoc } from './InfiniteMarqueeDoc'
export { default as CarouselDoc } from './CarouselDoc'
export { default as ModalDoc } from './ModalDoc'
export { default as ProductCardDoc } from './ProductCardDoc'
export { default as ProductModalDoc } from './ProductModalDoc'
export { default as ShoppingCartDoc } from './ShoppingCartDoc'
export { default as CalendarDoc } from './CalendarDoc'
export { default as ServiceCardDoc } from './ServiceCardDoc'
export { default as SearchBarDoc } from './SearchBarDoc'
export { default as QuantityPickerDoc } from './QuantityPickerDoc'
export { default as ButtonDoc } from './ButtonDoc'
export { default as FadeOverlayDoc } from './FadeOverlayDoc'
export { default as BackgroundVideoDoc } from './BackgroundVideoDoc'
// New component docs
export { default as CardDoc } from './CardDoc'
export { default as StoreCardDoc } from './StoreCardDoc'
export { default as FormInputDoc } from './FormInputDoc'
export { default as ImageGalleryDoc } from './ImageGalleryDoc'
export { default as DropdownDoc } from './DropdownDoc'
export { default as LoaderDoc } from './LoaderDoc'
export { default as AlertDoc } from './AlertDoc'

